// frontend/src/pages/Operations.jsx
// frontend/src/pages/Operations.jsx
import React, { useEffect, useState } from 'react'
import { api, fetchInventoryItems } from '../lib/api'
import { BRAND } from '../lib/constants'
import DashboardMap from '../components/DashboardMap'
import AssetDetailModal from '../components/AssetDetailModal'

export default function Operations() {
  const [assets, setAssets] = useState([])
  const [bases, setBases] = useState([])
  const [missions, setMissions] = useState([])
  const [inventory, setInventory] = useState([])
  const [baseWeather, setBaseWeather] = useState({})
  const [selectedAsset, setSelectedAsset] = useState(null)
  const [loading, setLoading] = useState(true)

  // Layer toggles
  const [layers, setLayers] = useState({
    assets: true,
    bases: true,
    geofences: true,
    threats: false,
    weather: false,
    missions: true
  })

  useEffect(() => {
    const fetchData = async () => {
      try {
        const [assetsData, basesData, missionsData, inventoryData] = await Promise.all([
          api.assets(),
          api.facilities(),
          api.missions(),
          fetchInventoryItems()
        ])
        setAssets(assetsData || [])
        setBases(basesData || [])
        setMissions(missionsData || [])
        setInventory(inventoryData || [])
        setLoading(false)
      } catch (err) {
        console.error('[Operations] Error:', err)
        setLoading(false)
      }
    }
    fetchData()
    const interval = setInterval(fetchData, 5000)
    return () => clearInterval(interval)
  }, [])

  const loadBaseWeather = async (base) => {
    const id = base.id
    if (baseWeather[id]?.loading) return
    setBaseWeather(prev => ({ ...prev, [id]: { loading: true, err: null, data: null } }))
    try {
      let data = null
      if (api.weatherByBase) {
        try { data = await api.weatherByBase(base.id) } catch (e) { console.warn(e) }
      }
      if (!data) data = await api.weather(base.lat, base.lon)
      setBaseWeather(prev => ({ ...prev, [id]: { loading: false, err: null, data } }))
    } catch (err) {
      setBaseWeather(prev => ({ ...prev, [id]: { loading: false, err, data: null } }))
    }
  }

  const toggleLayer = (layer) => {
    setLayers(prev => ({ ...prev, [layer]: !prev[layer] }))
  }

  if (loading) {
    return <div style={{ padding: 20, textAlign: 'center', color: BRAND.primary }}>Loading resource map...</div>
  }

  return (
    <div style={{
      height: 'calc(100vh - 120px)',
      display: 'flex',
      flexDirection: 'column'
    }}>
      {/* Header */}
      <div style={{
        display: 'flex',
        justifyContent: 'space-between',
        alignItems: 'center',
        marginBottom: '1rem'
      }}>
        <h1 style={{ fontSize: '1.5rem', color: '#e0e0e0', margin: 0 }}>
          🗺️ Resource Map - Live Asset Tracking
        </h1>
        <div style={{ display: 'flex', gap: '0.75rem' }}>
          <button style={buttonStyle}>Layers</button>
          <button style={buttonStyle}>Filters</button>
          <select style={selectStyle}>
            <option>LIVE</option>
            <option>Playback</option>
          </select>
        </div>
      </div>

      {/* Layer Controls */}
      <div style={{
        display: 'flex',
        gap: '1.5rem',
        padding: '1rem',
        background: '#1a1f2e',
        borderRadius: '8px',
        marginBottom: '1rem'
      }}>
        {Object.entries(layers).map(([key, value]) => (
          <label key={key} style={{
            display: 'flex',
            alignItems: 'center',
            gap: '0.5rem',
            color: '#a0aec0',
            cursor: 'pointer',
            fontSize: '0.9rem'
          }}>
            <input
              type="checkbox"
              checked={value}
              onChange={() => toggleLayer(key)}
            />
            <span>{value ? '✓' : '☐'} {key.charAt(0).toUpperCase() + key.slice(1)}</span>
          </label>
        ))}
      </div>

      {/* Map Container */}
      <div style={{
        flex: 1,
        background: '#1a1f2e',
        border: '2px solid #2d3748',
        borderRadius: '12px',
        overflow: 'hidden'
      }}>
        <DashboardMap
          assets={layers.assets ? assets : []}
          bases={layers.bases ? bases : []}
          missions={layers.missions ? missions : []}
          inventory={inventory}
          baseWeather={baseWeather}
          loadBaseWeather={loadBaseWeather}
          setSelectedAsset={setSelectedAsset}
        />
      </div>

      {/* Asset Detail Modal */}
      {selectedAsset && (
        <AssetDetailModal
          asset={selectedAsset}
          onClose={() => setSelectedAsset(null)}
        />
      )}
    </div>
  )
}

const buttonStyle = {
  padding: '0.6rem 1.2rem',
  background: '#2d3748',
  color: '#e0e0e0',
  border: '1px solid #4a5568',
  borderRadius: '6px',
  cursor: 'pointer',
  transition: 'all 0.2s'
}

const selectStyle = {
  padding: '0.6rem 1rem',
  background: '#2d3748',
  color: '#e0e0e0',
  border: '1px solid #4a5568',
  borderRadius: '6px',
  cursor: 'pointer'
}

// Aegis/frontend/src/routes/operations/+page.svelte
<!-- frontend/src/routes/operations/+page.svelte -->
<script>
  // TODO: Move your existing full map component here
  // This will be your main operational picture view
</script>

<div class="operations-page">
  <div class="page-header">
    <h1>🗺️ Operations - Common Operational Picture</h1>
    <div class="controls">
      <button class="btn">Layers</button>
      <button class="btn">Filters</button>
      <select class="time-select">
        <option>LIVE</option>
        <option>Playback</option>
      </select>
    </div>
  </div>

  <!-- Layer Toggles -->
  <div class="layer-controls">
    <label><input type="checkbox" checked> ✓ Assets</label>
    <label><input type="checkbox" checked> ✓ Bases</label>
    <label><input type="checkbox" checked> ✓ Geofences</label>
    <label><input type="checkbox"> ☐ Threats</label>
    <label><input type="checkbox"> ☐ Weather</label>
    <label><input type="checkbox"> ☐ Missions</label>
  </div>

  <!-- Map Container -->
  <div class="map-container">
    <p style="text-align: center; padding: 4rem; color: #718096;">
      📍 Move your existing map component here from the dashboard
    </p>
  </div>
</div>

<style>
  .operations-page {
    height: calc(100vh - 120px);
    display: flex;
    flex-direction: column;
  }

  .page-header {
    display: flex;
    justify-content: space-between;
    align-items: center;
    margin-bottom: 1rem;
  }

  .page-header h1 {
    font-size: 1.5rem;
    color: #e0e0e0;
  }

  .controls {
    display: flex;
    gap: 0.75rem;
  }

  .btn {
    padding: 0.6rem 1.2rem;
    background: #2d3748;
    color: #e0e0e0;
    border: 1px solid #4a5568;
    border-radius: 6px;
    cursor: pointer;
    transition: all 0.2s;
  }

  .btn:hover {
    background: #4a5568;
  }

  .time-select {
    padding: 0.6rem 1rem;
    background: #2d3748;
    color: #e0e0e0;
    border: 1px solid #4a5568;
    border-radius: 6px;
    cursor: pointer;
  }

  .layer-controls {
    display: flex;
    gap: 1.5rem;
    padding: 1rem;
    background: #1a1f2e;
    border-radius: 8px;
    margin-bottom: 1rem;
  }

  .layer-controls label {
    display: flex;
    align-items: center;
    gap: 0.5rem;
    color: #a0aec0;
    cursor: pointer;
    font-size: 0.9rem;
  }

  .map-container {
    flex: 1;
    background: #1a1f2e;
    border: 2px solid #2d3748;
    border-radius: 12px;
    overflow: hidden;
  }
</style>
